Implement mongodb for order service
pascalbenschopTU/WDM_project pull request #12
Opened 2023-05-15 17:52 UTC by pascalbenschopTU

2023-05-15 17:57 UTC, pascalbenschopTU commented
The init-mongo.js script in /order is called the first time you call docker-compose. It inserts a user into the database from volume order_mongodb_data, if you want to redo the script you have to delete the volume in docker.

2023-05-15 19:01 UTC, pascalbenschopTU commented
Sometimes the test failed with substract_stock 14 != 15, no clue why but rerunning the test fixes it.

2023-05-16 12:33 UTC, Nobert1 requested changes

2023-05-16 12:33 UTC, Nobert1 commented on order/app.py
> +app.config["MONGO_URI"] = 'mongodb://' + os.environ['MONGODB_USERNAME'] + ':' + os.environ['MONGODB_PASSWORD'] + '@' + os.environ['MONGODB_HOSTNAME'] + ':27017/' + os.environ['MONGODB_DATABASE']
Can i suggest using formatted string litterals instead? So f"mongodb://{os.environ['MONGODB_USERNAME']}:{os.environ['MONGODB_PASSWORD']}@{os.environ['MONGODB_HOSTNAME']}:27017/{os.environ['MONGODB_DATABASE']}". Doesn't make a difference i just think it's cleaner than using +

2023-05-16 15:47 UTC, LeonKempen commented
> Sometimes the test failed with substract_stock 14 != 15, no clue why but rerunning the test fixes it.

Well that is something that we should look into. Otherwise this would mean that the db is sometimes not consistent with even one user. Do you know if this already occured before you made the mongodb changes?

2023-05-16 15:53 UTC, Nobert1 commented
> > Sometimes the test failed with substract_stock 14 != 15, no clue why but rerunning the test fixes it.
> 
> Well that is something that we should look into. Otherwise this would mean that the db is sometimes not consistent with even one user. Do you know if this already occured before you made the mongodb changes?

It did occur before the changes.
The current implementation only has "eventual" consistency. If the operation is performed, and the stock consumer has not yet processed the message to return the stock, and put it in the database before the next read operation, the stock will not be updated. So it's random if it passes this test or not at this given time. Adding a small sleep before reading the stock agian will probably fix this.

2023-05-18 18:39 UTC, Nobert1 approved these changes

2023-05-18 20:24 UTC, merged